---
title: "Radiology Daily Process"
output: html_document
date: '2022-06-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages}
# Load packages ----------------------------------------------------------------
suppressMessages({
  memory.limit(size = 10000000)
  library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  #library(zipcode)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(feather)
  # library(zipcodeR)
  library(formattable)
  library(shinyjs)
  library(janitor)
  library(patchwork)
})

```


```{r Daily Processing}

dir_path <- "/data/Radiology"

# 1. Read in daily radiology data -------------------------------------------------
daily_data <- read_xls(list.files("/data/Radiology/data_upload",
                           pattern="mshp_Ambulatory.*\\.xls$", 
                           full.names=TRUE)) # Read in data that starts with "mshs_Ambulatory"

# Import in site mapping crosswalk --------------------------------------------- 
site_mappings <- read_csv("radiology_site_mapping.csv")

# Data Processing --------------------------------------------------------------
## Processing Function =========================================================
daily_process <- function(data){
  # Rename columns to resemble Epic patient access data (historical_data)
  original.cols <- c("DepartmentCode","Modality","requestor","Exam",
                     "SchedOnDTTM","DurationMinutes",
                     "Scheduled","Arrival","Begin","Complete","Depart","Cancel",
                     "Reason","DOB","Mrn","Preliminary","Finalized",
                     "Zip","ExamStatus","OrgCode")
  
  new.cols <- c("DepartmentCode","Modality","Requestor","Exam",
                     "Appt.Made.DTTM","Appt.Dur",
                     "Appt.DTTM","Arrived.DTTM","Begin.DTTM","Complete.DTTM","Depart.DTTM","Cancel.DTTM",
                     "Cancel.Reason","Birth.Date","MRN","Preliminary.DTTM","Finalized.DTTM",
                     "Zip.Code","ExamStatus","OrgCode")
  
  data <- data[original.cols]
  colnames(data) <- new.cols
  
  # Creating additional columns for analysis
  data$Campus <- site_mappings$Campus[match(data$OrgCode, site_mappings$ID)] # Map Campus Names
  data <- data %>%
    mutate(Department = "Radiology",
           Appt.DateYear = as.Date(Appt.DTTM, format="%Y-%m-%d"),
           Appt.MonthYear = format(Appt.DateYear, "%Y-%m"),
           Appt.Date = format(Appt.DateYear, "%m-%d"),
           Appt.Year = format(Appt.DateYear, "%Y"),
           Appt.Month = format(Appt.DateYear, "%b"),
           Appt.Quarter = quarters(Appt.DateYear),
           Appt.Week = floor_date(Appt.DateYear, unit="week", week_start = 1),
           Appt.Day = format(Appt.DateYear, "%a"),
           Appt.Time = format(as.POSIXct(as.ITime(Appt.DTTM, format = "%H:%M")), "%H:%M"),
           Appt.TM.Hr = format(strptime(as.ITime(floor_date(Appt.DTTM, "hour")), "%H:%M:%S"),'%H:%M'),
           Lead.Days = as.Date(Appt.DTTM, format="%Y-%m-%d")-as.Date(Cancel.DTTM, format="%Y-%m-%d"),
           Wait.Time = as.Date(Appt.DTTM, format="%Y-%m-%d")-as.Date(Appt.Made.DTTM, format="%Y-%m-%d")
    )
}


## Processed data output =======================================================
daily_data_processed <- daily_process(daily_data)

# Import in radiology_historical_data ------------------------------------------
repo_data <- readRDS(paste0(dir_path,"/radiology_historical_data.rds"))

# Merge daily processed data with historical data ------------------------------
merged_data <- bind_rows(repo_data, daily_data_processed)
merged_data <- distinct(merged_data)

# Write out appended radiology data --------------------------------------------
saveRDS(merged_data, paste0(dir_path, "/radiology_historical_data.rds"))

```

